services:
  mysql:
    image: mysql:8.0
    container_name: agms-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  serviceregistry:
    build:
      context: ./serviceregistry
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=default

  configserver:
    build:
      context: ./configserver
    ports:
      - "8888:8888"
    depends_on:
      serviceregistry:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=git
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
