CREATE DATABASE IF NOT EXISTS agms_auth;
CREATE DATABASE IF NOT EXISTS agms_zone;
CREATE DATABASE IF NOT EXISTS agms_crop;
CREATE DATABASE IF NOT EXISTS agms_automation;
CREATE DATABASE IF NOT EXISTS agms_sensor;
