spring.application.name=sensor-service
spring.config.import=optional:configserver:http://localhost:8888

# FIX: change port
server.port=8081

# Fallback values
external.iot.base-url=http://localhost:8081
external.iot.username=default_user
external.iot.password=default_pass